### ISSUE TITLE
Creating records using POST

### ISSUE THREAD

**Issue by morrigan** [gte451f/phalcon-json-api#3]
It seems that I can't find a way to create a new record. 

Acording to JSON API specification, the request to create a new user should go like this:
```POST /users HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "users",
    "attributes": {
      "firstName": "Ember",
      "lastName: "Hamster"
      "secert": "My biggest secret"
    }
  }
}
```

but the response is an array containing Phalcon information about PDO and other internal stuff.

Am I missing something? It seems like a great project and would be very useful it can be used as boilerplate :)

**Comment by gte451f** [comment]
Hi @morrigan I should warn you that this application is quite old.  I've made a number of improvements to the API package that drives this project but have not returned to this application to update it in light of the underlying API changes.  You might consider checking out this application for a better look at what the latest API looks like:
https://github.com/gte451f/smores-api

A few notes:
That project runs on a docker container so it's easier to get running (if you docker)
That project also adheres to 1.0 JSON API standards whereas this project was written while the standard was still taking shape.
The core project is a composer package that makes is easy to write standards compliant JSON API server which is this guy: https://github.com/gte451f/phalcon-json-api-package

**Comment by gte451f** [comment]
@morrigan I got motivated and updated this project so it should work with the latest version of the JSON API.  I even tested your post example and got it working after correcting a couple of typos.

I should start by saying, use the docker file included with this project, it's much easier to get the application up and running than having to fiddle with everything yourself.

Also, for a SQLITE file, make sure the web user has R/W perms on the file and enclosing folder.

Also, Also, you will want to update your composer packages.

So after cloning the repo (and assuming Docker is installed on your machine)...

```
cd YOUR-APP-ROOT;
# start composer containers
docker-compose up;
# set perms on sqlite database
chmod 777 -Rf app/database;
# run this if you need to update your composer packages
docker exec phalconjsonapi_php_1 composer install;
```

Posting this as you described:
```
{   
  "data": {     
    "type": "users",     
    "attributes": {       
      "firstName": "Ember",       
      "lastName": "Hamster",
      "secret": "My biggest secret"
    }   
  } 
}
```

Generated this result for me:
```
{
  "data": {
    "id": "16",
    "type": "users",
    "attributes": {
      "secret": "My biggest secret",
      "first-name": "Ember",
      "last-name": "Hamster"
    }
  },
  "meta": {
    "total_pages": 1,
    "total_record_count": 1,
    "returned_record_count": 1,
    "database_query_count": 7,
    "stopwatch": {
      "total_run_time": "99.37 ms",
      "laps": {
        "Booting App": "0.08 ms",
        "Loading Routes": "0.46 ms",
        "Processing Request": "98.56 ms",
        "Gathering Records": "0.15 ms",
        "Formatting Output": "0.1 ms"
      }
    }
  }
}
```

**Comment by gte451f** [comment]
At the risk of swamping you with information, I noticed you are using Ember.  The API package can be configured to support either JSON API or ActiveModel.

**Comment by morrigan** [comment]
@gte451f thanks! Great contribution to the Phalcon community ;)
